# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tock < Formula
  desc "Tock v1.6.4 is a simple timetracker for the command line"
  homepage "https://github.com/kriuchkov/tock"
  version "1.6.4"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kriuchkov/tock/releases/download/v1.6.4/tock_Darwin_x86_64.tar.gz"
      sha256 "a1b19a45d14d1245d93c36f6de68c1d16a51f73b4be8646aae49e2213abed70d"

      def install
        bin.install "tock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kriuchkov/tock/releases/download/v1.6.4/tock_Darwin_arm64.tar.gz"
      sha256 "6c30bc4271afa076996036a4f6bf4ed7a4d4f38d63cab2a31711c745e38730f8"

      def install
        bin.install "tock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kriuchkov/tock/releases/download/v1.6.4/tock_Linux_x86_64.tar.gz"
      sha256 "28c6399130e2f0a87c664670d1ffff56b9c8d4ee55b1c6fafba51bf85bf609ec"
      def install
        bin.install "tock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kriuchkov/tock/releases/download/v1.6.4/tock_Linux_arm64.tar.gz"
      sha256 "9019eba2af7681159abc36002a35a69523ad379ecbde79770b8563966f3dba6c"
      def install
        bin.install "tock"
      end
    end
  end

  test do
    system "#{bin}/tock version"
  end
end
