# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tock < Formula
  desc "Tock v1.2.0 is a simple timetracker for the command line"
  homepage "https://github.com/kriuchkov/tock"
  version "1.2.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kriuchkov/tock/releases/download/v1.2.0/tock_Darwin_x86_64.tar.gz"
      sha256 "627e9ed402e181cfb952294155d0f4055575ab74f53e5f824a94299fec7be062"

      def install
        bin.install "tock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kriuchkov/tock/releases/download/v1.2.0/tock_Darwin_arm64.tar.gz"
      sha256 "17ce349369f5ebff8302a050105ca0660719da62f1c89ccac17a33285ba36435"

      def install
        bin.install "tock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kriuchkov/tock/releases/download/v1.2.0/tock_Linux_x86_64.tar.gz"
      sha256 "0ae23cbdbf4a927934144e1f598d4e01779be23d364f094ecff18858929320b1"
      def install
        bin.install "tock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kriuchkov/tock/releases/download/v1.2.0/tock_Linux_arm64.tar.gz"
      sha256 "2f47bcc082fcaaa74e69fa92844caacb7a11f450ecfb96a37b8bbe8b0039ffdc"
      def install
        bin.install "tock"
      end
    end
  end

  test do
    system "#{bin}/tock version"
  end
end
