# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tock < Formula
  desc "Tock v1.7.14 is a simple timetracker for the command line"
  homepage "https://github.com/kriuchkov/tock"
  version "1.7.14"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kriuchkov/tock/releases/download/v1.7.14/tock_Darwin_x86_64.tar.gz"
      sha256 "ddd190a83cf9d93d03570d099f7dfcd00e980678c41bc80d30eb7e50acbd02c4"

      define_method(:install) do
        bin.install "tock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kriuchkov/tock/releases/download/v1.7.14/tock_Darwin_arm64.tar.gz"
      sha256 "ba3fed2929878b5afdea145464571ad0441534cdf58cc1177bc356b78f1c45ce"

      define_method(:install) do
        bin.install "tock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kriuchkov/tock/releases/download/v1.7.14/tock_Linux_x86_64.tar.gz"
      sha256 "c497e5b1482b1cda03794240e9645cdf6218bf2795d38fd6d3610bdcc847e295"
      define_method(:install) do
        bin.install "tock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kriuchkov/tock/releases/download/v1.7.14/tock_Linux_arm64.tar.gz"
      sha256 "c2d85736185d9fb707a7ad6d3c5b2efd972950b8e2cfd5fbefdd16ab00f3e744"
      define_method(:install) do
        bin.install "tock"
      end
    end
  end

  test do
    system "#{bin}/tock version"
  end
end
